#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FoliageOnPlot_Junk_Sign

#include "Basic.hpp"

#include "BP_FoliageOnPlot_Junk_Sign_classes.hpp"
#include "BP_FoliageOnPlot_Junk_Sign_parameters.hpp"


namespace SDK
{

// Function BP_FoliageOnPlot_Junk_Sign.BP_FoliageOnPlot_Junk_Sign_C.ExecuteUbergraph_BP_FoliageOnPlot_Junk_Sign
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TDelegate<void()>                       K2Node_CreateDelegate_OutputDelegate                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AValeriaCharacter*                CallFunc_WaitForValeriaCharacter_valeriaCharacter      (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AValeriaPlayerController*         CallFunc_GetValeriaPlayerController_ReturnValue        (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsInCinematicMode_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCinematicManagerComponent*       CallFunc_GetCinematicManager_ReturnValue               (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_HasAuthority_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_StrStr_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_StrStr_ReturnValue_1               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TDelegate<void()>                       K2Node_CreateDelegate_OutputDelegate_1                 (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_FoliageOnPlot_Junk_Sign_C::ExecuteUbergraph_BP_FoliageOnPlot_Junk_Sign(int32 EntryPoint, TDelegate<void()> K2Node_CreateDelegate_OutputDelegate, class AValeriaCharacter* CallFunc_WaitForValeriaCharacter_valeriaCharacter, bool CallFunc_IsValid_ReturnValue, class AValeriaPlayerController* CallFunc_GetValeriaPlayerController_ReturnValue, bool CallFunc_IsInCinematicMode_ReturnValue, class UCinematicManagerComponent* CallFunc_GetCinematicManager_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue_1, TDelegate<void()> K2Node_CreateDelegate_OutputDelegate_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FoliageOnPlot_Junk_Sign_C", "ExecuteUbergraph_BP_FoliageOnPlot_Junk_Sign");

	Params::BP_FoliageOnPlot_Junk_Sign_C_ExecuteUbergraph_BP_FoliageOnPlot_Junk_Sign Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_CreateDelegate_OutputDelegate = K2Node_CreateDelegate_OutputDelegate;
	Parms.CallFunc_WaitForValeriaCharacter_valeriaCharacter = CallFunc_WaitForValeriaCharacter_valeriaCharacter;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_GetValeriaPlayerController_ReturnValue = CallFunc_GetValeriaPlayerController_ReturnValue;
	Parms.CallFunc_IsInCinematicMode_ReturnValue = CallFunc_IsInCinematicMode_ReturnValue;
	Parms.CallFunc_GetCinematicManager_ReturnValue = CallFunc_GetCinematicManager_ReturnValue;
	Parms.CallFunc_HasAuthority_ReturnValue = CallFunc_HasAuthority_ReturnValue;
	Parms.CallFunc_EqualEqual_StrStr_ReturnValue = CallFunc_EqualEqual_StrStr_ReturnValue;
	Parms.CallFunc_EqualEqual_StrStr_ReturnValue_1 = CallFunc_EqualEqual_StrStr_ReturnValue_1;
	Parms.K2Node_CreateDelegate_OutputDelegate_1 = K2Node_CreateDelegate_OutputDelegate_1;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FoliageOnPlot_Junk_Sign.BP_FoliageOnPlot_Junk_Sign_C.OnCinLevelLoaded_Event
// (BlueprintCallable, BlueprintEvent)

void ABP_FoliageOnPlot_Junk_Sign_C::OnCinLevelLoaded_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FoliageOnPlot_Junk_Sign_C", "OnCinLevelLoaded_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FoliageOnPlot_Junk_Sign.BP_FoliageOnPlot_Junk_Sign_C.OnCinLevelUnloaded_Event
// (BlueprintCallable, BlueprintEvent)

void ABP_FoliageOnPlot_Junk_Sign_C::OnCinLevelUnloaded_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FoliageOnPlot_Junk_Sign_C", "OnCinLevelUnloaded_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FoliageOnPlot_Junk_Sign.BP_FoliageOnPlot_Junk_Sign_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FoliageOnPlot_Junk_Sign_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FoliageOnPlot_Junk_Sign_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FoliageOnPlot_Junk_Sign.BP_FoliageOnPlot_Junk_Sign_C.ShouldUseISM
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_ShouldUseISM                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FoliageOnPlot_Junk_Sign_C::ShouldUseISM(bool* Param_ShouldUseISM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FoliageOnPlot_Junk_Sign_C", "ShouldUseISM");

	Params::BP_FoliageOnPlot_Junk_Sign_C_ShouldUseISM Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ShouldUseISM != nullptr)
		*Param_ShouldUseISM = Parms.Param_ShouldUseISM;
}

}

