#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NotificationInterface_SyncInvite_Received

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_NotificationInterface_SyncInvite_Received.BP_NotificationInterface_SyncInvite_Received_C.InitPrePushNotification
// 0x0008 (0x0008 - 0x0000)
struct BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification final
{
public:
	class UInvitation*                            Invitation;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification) == 0x000008, "Wrong alignment on BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification");
static_assert(sizeof(BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification) == 0x000008, "Wrong size on BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification");
static_assert(offsetof(BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification, Invitation) == 0x000000, "Member 'BP_NotificationInterface_SyncInvite_Received_C_InitPrePushNotification::Invitation' has a wrong offset!");

}

