#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VillagerTheArchaeologist_Intro

#include "Basic.hpp"

#include "BP_ValeriaVillagerCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VillagerTheArchaeologist_Intro.BP_VillagerTheArchaeologist_Intro_C
// 0x0000 (0x08B0 - 0x08B0)
class ABP_VillagerTheArchaeologist_Intro_C final : public ABP_ValeriaVillagerCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VillagerTheArchaeologist_Intro_C">();
	}
	static class ABP_VillagerTheArchaeologist_Intro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VillagerTheArchaeologist_Intro_C>();
	}
};
static_assert(alignof(ABP_VillagerTheArchaeologist_Intro_C) == 0x000010, "Wrong alignment on ABP_VillagerTheArchaeologist_Intro_C");
static_assert(sizeof(ABP_VillagerTheArchaeologist_Intro_C) == 0x0008B0, "Wrong size on ABP_VillagerTheArchaeologist_Intro_C");

}

