#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ValeriaVillagerController

#include "Basic.hpp"

#include "Palia_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ValeriaVillagerController.BP_ValeriaVillagerController_C
// 0x0008 (0x05D0 - 0x05C8)
class ABP_ValeriaVillagerController_C final : public AValeriaVillagerController
{
public:
	class FName                                   HomeLocation;                                      // 0x05C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ValeriaVillagerController_C">();
	}
	static class ABP_ValeriaVillagerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ValeriaVillagerController_C>();
	}
};
static_assert(alignof(ABP_ValeriaVillagerController_C) == 0x000008, "Wrong alignment on ABP_ValeriaVillagerController_C");
static_assert(sizeof(ABP_ValeriaVillagerController_C) == 0x0005D0, "Wrong size on ABP_ValeriaVillagerController_C");
static_assert(offsetof(ABP_ValeriaVillagerController_C, HomeLocation) == 0x0005C8, "Member 'ABP_ValeriaVillagerController_C::HomeLocation' has a wrong offset!");

}

