#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_VisibilityChanges

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_VisibilityChanges.BPI_VisibilityChanges_C.S6OnVisibilityChanged
// 0x0001 (0x0001 - 0x0000)
struct BPI_VisibilityChanges_C_S6OnVisibilityChanged final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_VisibilityChanges_C_S6OnVisibilityChanged) == 0x000001, "Wrong alignment on BPI_VisibilityChanges_C_S6OnVisibilityChanged");
static_assert(sizeof(BPI_VisibilityChanges_C_S6OnVisibilityChanged) == 0x000001, "Wrong size on BPI_VisibilityChanges_C_S6OnVisibilityChanged");
static_assert(offsetof(BPI_VisibilityChanges_C_S6OnVisibilityChanged, IsVisible) == 0x000000, "Member 'BPI_VisibilityChanges_C_S6OnVisibilityChanged::IsVisible' has a wrong offset!");

}

