#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_CreatureAudioEvents

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_CreatureAudioEvents.E_CreatureAudioEvents
// NumValues: 0x000E
enum class E_CreatureAudioEvents : uint8
{
	NewEnumerator7                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator8                           = 4,
	NewEnumerator3                           = 5,
	NewEnumerator4                           = 6,
	NewEnumerator5                           = 7,
	NewEnumerator6                           = 8,
	NewEnumerator13                          = 9,
	NewEnumerator15                          = 10,
	NewEnumerator16                          = 11,
	NewEnumerator17                          = 12,
	E_MAX                                    = 13,
};

}

