#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerCharacterInspectionCard_CM

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "Palia_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "OnlineSubsystemValeria_structs.hpp"


namespace SDK::Params
{

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_BndEvt__WBP_PlayerCharacterInspectionCard_CM_WBP_Template_Button_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM
// 0x03B0 (0x03B0 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5663[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAuthManager*                           CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5664[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       CallFunc_GetNetId_ReturnValue;                     // 0x0018(0x0030)(HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5665[0x2];                                     // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0050(0x0018)()
	struct FGuid                                  Temp_struct_Variable;                              // 0x0068(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0078(0x0050)(HasGetValueTypeHash)
	TArray<struct FOSSVAL_CharacterNameAndId>     Temp_struct_Variable_1;                            // 0x00C8(0x0010)(ReferenceParm)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E8(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0100(0x0018)()
	struct FGuid                                  K2Node_CustomEvent_AccountId;                      // 0x0118(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FOSSVAL_CharacterNameAndId>     K2Node_CustomEvent_Names;                          // 0x0128(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_IsValid_Guid_ReturnValue;                 // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_Guid_ReturnValue_1;               // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x013A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x013B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x013C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x013D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x013E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x013F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_Guid_ReturnValue_2;               // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5666[0x3];                                     // 0x0141(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FGuid& AccountId, TArray<struct FOSSVAL_CharacterNameAndId>& Names)> K2Node_CreateDelegate_OutputDelegate;              // 0x0144(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  K2Node_CustomEvent_AccountId_1;                    // 0x0154(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  CallFunc_GetAccountId_ReturnValue;                 // 0x0164(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5667[0x4];                                     // 0x0174(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOSSVAL_GetCharacterNamesByAccountIdProxy* CallFunc_GetCharacterNamesByAccountId_ReturnValue; // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGuid& AccountId)>      K2Node_CreateDelegate_OutputDelegate_1;            // 0x0180(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5668[0x3];                                     // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_AkEventGlobal_ReturnValue;                // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FUniqueNetIdRepl& BlockedNetId, bool bBlocked)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0198(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FUniqueNetIdRepl& BlockedNetId, bool bBlocked)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x01A8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_Block_ModalDialogue_CM_C*          CallFunc_Create_ReturnValue;                       // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Block_ModalDialogue_PF_C*          CallFunc_Create_ReturnValue_1;                     // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class US6UI_UIManagerWidgetBase*              CallFunc_GetUIManagerWidget_ReturnValue;           // 0x01D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5669[0x7];                                     // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UVAL_FriendsManager*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x01E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566A[0x6];                                     // 0x01FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UVAL_FriendsManager*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_2;    // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0208(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_ReportPlayerModalDialog_CM_C*      CallFunc_Create_ReturnValue_2;                     // 0x0210(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_ReportPlayerModalDialog_PF_C*      CallFunc_Create_ReturnValue_3;                     // 0x0218(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class US6UI_UIManagerWidgetBase*              CallFunc_GetUIManagerWidget_ReturnValue_1;         // 0x0220(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsole_ReturnValue;                    // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0229(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566B[0x6];                                     // 0x022A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UVAL_FriendsManager*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_3;    // 0x0230(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EVAL_SocialBlockError                         CallFunc_RequestBlockUser_ReturnValue;             // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566C[0x7];                                     // 0x0239(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, class FText>                Temp_name_Variable;                                // 0x0240(0x0050)()
	class UPresenceManager*                       CallFunc_GetLocalPlayerSubsystem_ReturnValue_4;    // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue_1;            // 0x0298(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPresence                              CallFunc_GetPresenceForUserId_ReturnValue;         // 0x02A0(0x00B0)()
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566D[0x3];                                     // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0354(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566E[0x4];                                     // 0x035C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Map_Find_Value;                           // 0x0360(0x0018)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_566F[0x7];                                     // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVAL_FriendsManager*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_5;    // 0x0380(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUserBlocked_ReturnValue;                // 0x0388(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ReturnValue;                   // 0x0389(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDesktop_ReturnValue;                    // 0x038A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x038B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsole_ReturnValue_1;                  // 0x038C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDesktop_ReturnValue_1;                  // 0x038D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x038E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x038F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SubWidgetFocusable_C> CallFunc_OnWidgetCreated_self_CastInput;           // 0x0390(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SubWidgetFocusable_C> CallFunc_OnWidgetCreated_self_CastInput_1;         // 0x03A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM) == 0x0003B0, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, EntryPoint) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_bool_Variable) == 0x000010, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetNetId_ReturnValue) == 0x000018, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetNetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_byte_Variable) == 0x000048, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_byte_Variable_1) == 0x000049, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Array_Length_ReturnValue) == 0x00004C, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Conv_IntToText_ReturnValue) == 0x000050, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_struct_Variable) == 0x000068, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_MakeStruct_FormatArgumentData) == 0x000078, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_struct_Variable_1) == 0x0000C8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_MakeArray_Array) == 0x0000D8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Format_ReturnValue) == 0x0000E8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Conv_StringToText_ReturnValue) == 0x000100, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CustomEvent_AccountId) == 0x000118, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CustomEvent_AccountId' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CustomEvent_Names) == 0x000128, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CustomEvent_Names' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsValid_Guid_ReturnValue) == 0x000138, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsValid_Guid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsValid_Guid_ReturnValue_1) == 0x000139, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsValid_Guid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Not_PreBool_ReturnValue) == 0x00013A, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Not_PreBool_ReturnValue_1) == 0x00013B, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_BooleanOR_ReturnValue) == 0x00013C, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_BooleanOR_ReturnValue_1) == 0x00013D, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_BooleanAND_ReturnValue) == 0x00013E, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_BooleanAND_ReturnValue_1) == 0x00013F, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsValid_Guid_ReturnValue_2) == 0x000140, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsValid_Guid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CreateDelegate_OutputDelegate) == 0x000144, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CustomEvent_AccountId_1) == 0x000154, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CustomEvent_AccountId_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetAccountId_ReturnValue) == 0x000164, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetAccountId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetCharacterNamesByAccountId_ReturnValue) == 0x000178, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetCharacterNamesByAccountId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CreateDelegate_OutputDelegate_1) == 0x000180, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsValid_ReturnValue) == 0x000190, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_AkEventGlobal_ReturnValue) == 0x000194, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_AkEventGlobal_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CreateDelegate_OutputDelegate_2) == 0x000198, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_CreateDelegate_OutputDelegate_3) == 0x0001A8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetOwningPlayer_ReturnValue) == 0x0001B8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Create_ReturnValue) == 0x0001C0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Create_ReturnValue_1) == 0x0001C8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetUIManagerWidget_ReturnValue) == 0x0001D0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_MakeLiteralByte_ReturnValue) == 0x0001D8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_ComponentBoundEvent_Button) == 0x0001E0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x0001E8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetActiveWidget_ReturnValue) == 0x0001F0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0001F8, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsVisible_ReturnValue) == 0x0001F9, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_2) == 0x000200, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000208, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Create_ReturnValue_2) == 0x000210, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Create_ReturnValue_3) == 0x000218, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetUIManagerWidget_ReturnValue_1) == 0x000220, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetUIManagerWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsConsole_ReturnValue) == 0x000228, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsConsole_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000229, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_3) == 0x000230, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_RequestBlockUser_ReturnValue) == 0x000238, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_RequestBlockUser_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, Temp_name_Variable) == 0x000240, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_4) == 0x000290, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetActiveWidget_ReturnValue_1) == 0x000298, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetActiveWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetPresenceForUserId_ReturnValue) == 0x0002A0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetPresenceForUserId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000350, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Conv_StringToName_ReturnValue) == 0x000354, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Map_Find_Value) == 0x000360, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_Map_Find_ReturnValue) == 0x000378, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_5) == 0x000380, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsUserBlocked_ReturnValue) == 0x000388, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsUserBlocked_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_EqualEqual_ReturnValue) == 0x000389, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_EqualEqual_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsDesktop_ReturnValue) == 0x00038A, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsDesktop_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, K2Node_Select_Default) == 0x00038B, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsConsole_ReturnValue_1) == 0x00038C, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsConsole_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_IsDesktop_ReturnValue_1) == 0x00038D, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_IsDesktop_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x00038E, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x00038F, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_OnWidgetCreated_self_CastInput) == 0x000390, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_OnWidgetCreated_self_CastInput' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM, CallFunc_OnWidgetCreated_self_CastInput_1) == 0x0003A0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_ExecuteUbergraph_WBP_PlayerCharacterInspectionCard_CM::CallFunc_OnWidgetCreated_self_CastInput_1' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandeQueryOurUserMembershipFailed
// 0x0010 (0x0010 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed final
{
public:
	class FString                                 ErrorMessage;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed) == 0x000010, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed, ErrorMessage) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipFailed::ErrorMessage' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandeQueryOurUserMembershipSucceeded
// 0x0120 (0x0120 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded final
{
public:
	bool                                          bHasMembership;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5670[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVAL_PlayerGuild                       PlayerGuild;                                       // 0x0008(0x0118)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded) == 0x000120, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded, bHasMembership) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded::bHasMembership' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded, PlayerGuild) == 0x000008, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryOurUserMembershipSucceeded::PlayerGuild' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandeQueryTheirUserMembershipFailed
// 0x0010 (0x0010 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed final
{
public:
	class FString                                 ErrorMessage;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed) == 0x000010, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed, ErrorMessage) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipFailed::ErrorMessage' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandeQueryTheirUserMembershipSucceeded
// 0x0120 (0x0120 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded final
{
public:
	bool                                          bHasMembership;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5671[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVAL_PlayerGuild                       PlayerGuild;                                       // 0x0008(0x0118)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded) == 0x000120, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded, bHasMembership) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded::bHasMembership' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded, PlayerGuild) == 0x000008, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandeQueryTheirUserMembershipSucceeded::PlayerGuild' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandleOnCharacterBlocked
// 0x0038 (0x0038 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked final
{
public:
	struct FUniqueNetIdRepl                       BlockedNetId;                                      // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
	bool                                          bBlocked;                                          // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ReturnValue;                   // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked) == 0x000038, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked, BlockedNetId) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked::BlockedNetId' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked, bBlocked) == 0x000030, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked::bBlocked' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked, CallFunc_EqualEqual_ReturnValue) == 0x000031, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandleOnCharacterBlocked::CallFunc_EqualEqual_ReturnValue' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.HandleQueryOurPlayerGuildRosterSucceeded
// 0x0118 (0x0118 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded final
{
public:
	struct FVAL_PlayerGuild                       PlayerGuild;                                       // 0x0000(0x0118)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded) == 0x000118, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded, PlayerGuild) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_HandleQueryOurPlayerGuildRosterSucceeded::PlayerGuild' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnBackButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature final
{
public:
	class UWBP_PlayerCharacterInspectionCard_CM_C* CharacterCardWidget;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature, CharacterCardWidget) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnBackButtonClicked__DelegateSignature::CharacterCardWidget' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnFailure_E68A415549054C67A3D2F2AC1DE76C48
// 0x0010 (0x0010 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48 final
{
public:
	struct FGuid                                  AccountId;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48) == 0x000004, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48) == 0x000010, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48, AccountId) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnFailure_E68A415549054C67A3D2F2AC1DE76C48::AccountId' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnSubWidgetClosed
// 0x0002 (0x0002 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed final
{
public:
	bool                                          FocusedParentWidget;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Param_NewWidgetCreated;                            // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed) == 0x000001, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed) == 0x000002, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed, FocusedParentWidget) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed::FocusedParentWidget' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed, Param_NewWidgetCreated) == 0x000001, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnSubWidgetClosed::Param_NewWidgetCreated' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnSuccess_E68A415549054C67A3D2F2AC1DE76C48
// 0x0020 (0x0020 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48 final
{
public:
	struct FGuid                                  AccountId;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FOSSVAL_CharacterNameAndId>     Names;                                             // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48) == 0x000020, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48, AccountId) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48::AccountId' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48, Names) == 0x000010, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnSuccess_E68A415549054C67A3D2F2AC1DE76C48::Names' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnVisibilityChangedEvent
// 0x0001 (0x0001 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent final
{
public:
	ESlateVisibility                              InVisibility;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent) == 0x000001, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent) == 0x000001, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent, InVisibility) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnVisibilityChangedEvent::InVisibility' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.OnWidgetCreated
// 0x0010 (0x0010 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated final
{
public:
	class UWidget*                                ParentWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                ParentFocusedWidget;                               // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated) == 0x000010, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated, ParentWidget) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated::ParentWidget' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated, ParentFocusedWidget) == 0x000008, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_OnWidgetCreated::ParentFocusedWidget' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.SetUser
// 0x00B8 (0x00B8 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_SetUser final
{
public:
	struct FUniqueNetIdRepl                       Param_UserId;                                      // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	TDelegate<void(const class FString& ErrorMessage)> K2Node_CreateDelegate_OutputDelegate;              // 0x0030(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bHasMembership, const struct FVAL_PlayerGuild& PlayerGuild)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0040(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& ErrorMessage)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0050(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bHasMembership, const struct FVAL_PlayerGuild& PlayerGuild)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x0060(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAuthManager*                           CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UVAL_PlayerGuildSubsystem*              CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       CallFunc_GetNetId_ReturnValue;                     // 0x0080(0x0030)(HasGetValueTypeHash)
	class UVAL_PlayerGuildSubsystem*              CallFunc_GetLocalPlayerSubsystem_ReturnValue_2;    // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_SetUser");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser) == 0x0000B8, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_SetUser");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, Param_UserId) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::Param_UserId' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, K2Node_CreateDelegate_OutputDelegate) == 0x000030, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, K2Node_CreateDelegate_OutputDelegate_1) == 0x000040, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, K2Node_CreateDelegate_OutputDelegate_2) == 0x000050, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, K2Node_CreateDelegate_OutputDelegate_3) == 0x000060, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000070, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x000078, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, CallFunc_GetNetId_ReturnValue) == 0x000080, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::CallFunc_GetNetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_SetUser, CallFunc_GetLocalPlayerSubsystem_ReturnValue_2) == 0x0000B0, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_SetUser::CallFunc_GetLocalPlayerSubsystem_ReturnValue_2' has a wrong offset!");

// Function WBP_PlayerCharacterInspectionCard_CM.WBP_PlayerCharacterInspectionCard_CM_C.UpdateOurPlayerGuildRoster
// 0x0160 (0x0160 - 0x0000)
struct WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster final
{
public:
	struct FVAL_PlayerGuild                       PlayerGuild;                                       // 0x0000(0x0118)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UVAL_PlayerGuildSubsystem*              CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAuthManager*                           CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       CallFunc_GetNetId_ReturnValue;                     // 0x0128(0x0030)(HasGetValueTypeHash)
	EVAL_PlayerGuildMemberRole                    CallFunc_TryGetRoleForUserId_OutRole;              // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryGetRoleForUserId_ReturnValue;          // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster) == 0x000008, "Wrong alignment on WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster");
static_assert(sizeof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster) == 0x000160, "Wrong size on WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, PlayerGuild) == 0x000000, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::PlayerGuild' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000118, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x000120, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, CallFunc_GetNetId_ReturnValue) == 0x000128, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::CallFunc_GetNetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, CallFunc_TryGetRoleForUserId_OutRole) == 0x000158, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::CallFunc_TryGetRoleForUserId_OutRole' has a wrong offset!");
static_assert(offsetof(WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster, CallFunc_TryGetRoleForUserId_ReturnValue) == 0x000159, "Member 'WBP_PlayerCharacterInspectionCard_CM_C_UpdateOurPlayerGuildRoster::CallFunc_TryGetRoleForUserId_ReturnValue' has a wrong offset!");

}

