#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TIM_ChatImageEmoji

#include "Basic.hpp"

#include "WBP_TIM_ChatImageEmoji_classes.hpp"
#include "WBP_TIM_ChatImageEmoji_parameters.hpp"


namespace SDK
{

// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.BndEvt__WBP_TIM_ChatEmoji_Emoji_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_TIM_ChatImageEmoji_C::BndEvt__WBP_TIM_ChatEmoji_Emoji_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "BndEvt__WBP_TIM_ChatEmoji_Emoji_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_TIM_ChatImageEmoji_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TIM_ChatImageEmoji_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "BP_OnItemExpansionChanged");

	Params::WBP_TIM_ChatImageEmoji_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TIM_ChatImageEmoji_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "BP_OnItemSelectionChanged");

	Params::WBP_TIM_ChatImageEmoji_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.ExecuteUbergraph_WBP_TIM_ChatImageEmoji
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UChatManager*                     CallFunc_GetLocalPlayerSubsystem_ReturnValue           (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_bIsExpanded                               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_bIsSelected                               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          K2Node_Event_ListItemObject                            (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UBP_TIM_ChatImageEmojiListItem_C* K2Node_DynamicCast_AsBP_TIM_Chat_Image_Emoji_List_Item (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             CallFunc_Conv_NameToText_ReturnValue                   ()
// struct FFormatArgumentData              K2Node_MakeStruct_FormatArgumentData                   (HasGetValueTypeHash)
// TArray<struct FFormatArgumentData>      K2Node_MakeArray_Array                                 (ReferenceParm)
// class FText                             CallFunc_Format_ReturnValue                            ()

void UWBP_TIM_ChatImageEmoji_C::ExecuteUbergraph_WBP_TIM_ChatImageEmoji(int32 EntryPoint, class UChatManager* CallFunc_GetLocalPlayerSubsystem_ReturnValue, bool K2Node_Event_bIsExpanded, bool K2Node_Event_bIsSelected, class UObject* K2Node_Event_ListItemObject, class UBP_TIM_ChatImageEmojiListItem_C* K2Node_DynamicCast_AsBP_TIM_Chat_Image_Emoji_List_Item, bool K2Node_DynamicCast_bSuccess, class FText CallFunc_Conv_NameToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "ExecuteUbergraph_WBP_TIM_ChatImageEmoji");

	Params::WBP_TIM_ChatImageEmoji_C_ExecuteUbergraph_WBP_TIM_ChatImageEmoji Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_GetLocalPlayerSubsystem_ReturnValue = CallFunc_GetLocalPlayerSubsystem_ReturnValue;
	Parms.K2Node_Event_bIsExpanded = K2Node_Event_bIsExpanded;
	Parms.K2Node_Event_bIsSelected = K2Node_Event_bIsSelected;
	Parms.K2Node_Event_ListItemObject = K2Node_Event_ListItemObject;
	Parms.K2Node_DynamicCast_AsBP_TIM_Chat_Image_Emoji_List_Item = K2Node_DynamicCast_AsBP_TIM_Chat_Image_Emoji_List_Item;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_Conv_NameToText_ReturnValue = CallFunc_Conv_NameToText_ReturnValue;
	Parms.K2Node_MakeStruct_FormatArgumentData = std::move(K2Node_MakeStruct_FormatArgumentData);
	Parms.K2Node_MakeArray_Array = std::move(K2Node_MakeArray_Array);
	Parms.CallFunc_Format_ReturnValue = CallFunc_Format_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	K2Node_MakeArray_Array = std::move(Parms.K2Node_MakeArray_Array);
}


// Function WBP_TIM_ChatImageEmoji.WBP_TIM_ChatImageEmoji_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_TIM_ChatImageEmoji_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TIM_ChatImageEmoji_C", "OnListItemObjectSet");

	Params::WBP_TIM_ChatImageEmoji_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}

}

