#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CarouselPaginator_CM

#include "Basic.hpp"

#include "WBP_CarouselPaginator_CM_classes.hpp"
#include "WBP_CarouselPaginator_CM_parameters.hpp"


namespace SDK
{

// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.Backward
// (BlueprintCallable, BlueprintEvent)

void UWBP_CarouselPaginator_CM_C::Backward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "Backward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_CarouselPaginator_CM_C_BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_CarouselPaginator_CM_C_BndEvt__WBP_CarouselPaginator_CM_Button_LeftArrow_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_CarouselPaginator_CM_C_BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_CarouselPaginator_CM_C_BndEvt__WBP_CarouselPaginator_CM_Button_RightArrow_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CarouselPaginator_CM_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.ExecuteUbergraph_WBP_CarouselPaginator_CM
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonButtonBase*                K2Node_ComponentBoundEvent_Button                      (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Greater_IntInt_ReturnValue                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Subtract_IntInt_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_AkEventGlobal_ReturnValue                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_AkEventGlobal_ReturnValue_1                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonButtonBase*                K2Node_ComponentBoundEvent_Button_3                    (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UCommonButtonBase*                K2Node_ComponentBoundEvent_Button_2                    (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UCommonButtonBase*                K2Node_ComponentBoundEvent_Button_1                    (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::ExecuteUbergraph_WBP_CarouselPaginator_CM(int32 EntryPoint, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_AkEventGlobal_ReturnValue, int32 CallFunc_AkEventGlobal_ReturnValue_1, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button_3, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button_2, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "ExecuteUbergraph_WBP_CarouselPaginator_CM");

	Params::WBP_CarouselPaginator_CM_C_ExecuteUbergraph_WBP_CarouselPaginator_CM Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_ComponentBoundEvent_Button = K2Node_ComponentBoundEvent_Button;
	Parms.CallFunc_Greater_IntInt_ReturnValue = CallFunc_Greater_IntInt_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_Subtract_IntInt_ReturnValue = CallFunc_Subtract_IntInt_ReturnValue;
	Parms.CallFunc_AkEventGlobal_ReturnValue = CallFunc_AkEventGlobal_ReturnValue;
	Parms.CallFunc_AkEventGlobal_ReturnValue_1 = CallFunc_AkEventGlobal_ReturnValue_1;
	Parms.K2Node_ComponentBoundEvent_Button_3 = K2Node_ComponentBoundEvent_Button_3;
	Parms.K2Node_ComponentBoundEvent_Button_2 = K2Node_ComponentBoundEvent_Button_2;
	Parms.K2Node_ComponentBoundEvent_Button_1 = K2Node_ComponentBoundEvent_Button_1;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.Forward
// (BlueprintCallable, BlueprintEvent)

void UWBP_CarouselPaginator_CM_C::Forward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "Forward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.GetActivePageIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_ActivePageIndex                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::GetActivePageIndex(int32* Param_ActivePageIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "GetActivePageIndex");

	Params::WBP_CarouselPaginator_CM_C_GetActivePageIndex Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ActivePageIndex != nullptr)
		*Param_ActivePageIndex = Parms.Param_ActivePageIndex;
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.HandleCarouselPageButtonClicked
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_CarouselPageButton_CM_C*     TutorialPageButton                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::HandleCarouselPageButtonClicked(class UWBP_CarouselPageButton_CM_C* TutorialPageButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "HandleCarouselPageButtonClicked");

	Params::WBP_CarouselPaginator_CM_C_HandleCarouselPageButtonClicked Parms{};

	Parms.TutorialPageButton = TutorialPageButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.OnActivePageChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_CarouselPaginator_CM_C*      CarouselPaginator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::OnActivePageChanged__DelegateSignature(class UWBP_CarouselPaginator_CM_C* CarouselPaginator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "OnActivePageChanged__DelegateSignature");

	Params::WBP_CarouselPaginator_CM_C_OnActivePageChanged__DelegateSignature Parms{};

	Parms.CarouselPaginator = CarouselPaginator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.SetActivePageIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_CarouselPagePip_CM_C*        CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Array_IsValidIndex_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_CarouselPagePip_CM_C*        CallFunc_Array_Get_Item_1                              (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Array_IsValidIndex_ReturnValue_1              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_NotEqual_IntInt_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::SetActivePageIndex(int32 NewValue, class UWBP_CarouselPagePip_CM_C* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UWBP_CarouselPagePip_CM_C* CallFunc_Array_Get_Item_1, bool CallFunc_Array_IsValidIndex_ReturnValue_1, bool CallFunc_NotEqual_IntInt_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "SetActivePageIndex");

	Params::WBP_CarouselPaginator_CM_C_SetActivePageIndex Parms{};

	Parms.NewValue = NewValue;
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Array_IsValidIndex_ReturnValue = CallFunc_Array_IsValidIndex_ReturnValue;
	Parms.CallFunc_Array_Get_Item_1 = CallFunc_Array_Get_Item_1;
	Parms.CallFunc_Array_IsValidIndex_ReturnValue_1 = CallFunc_Array_IsValidIndex_ReturnValue_1;
	Parms.CallFunc_NotEqual_IntInt_ReturnValue = CallFunc_NotEqual_IntInt_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.SetPageCount
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PageCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewActivePageIndex                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Variable                                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_CarouselPagePip_CM_C*        CallFunc_Create_ReturnValue                            (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Add_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UHorizontalBoxSlot*               CallFunc_AddChildToHorizontalBox_ReturnValue           (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Subtract_IntInt_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_LessEqual_IntInt_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CarouselPaginator_CM_C::SetPageCount(int32 PageCount, int32 NewActivePageIndex, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, int32 Temp_int_Variable, class UWBP_CarouselPagePip_CM_C* CallFunc_Create_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBox_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "SetPageCount");

	Params::WBP_CarouselPaginator_CM_C_SetPageCount Parms{};

	Parms.PageCount = PageCount;
	Parms.NewActivePageIndex = NewActivePageIndex;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.Temp_int_Variable = Temp_int_Variable;
	Parms.CallFunc_Create_ReturnValue = CallFunc_Create_ReturnValue;
	Parms.CallFunc_Array_Add_ReturnValue = CallFunc_Array_Add_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_AddChildToHorizontalBox_ReturnValue = CallFunc_AddChildToHorizontalBox_ReturnValue;
	Parms.CallFunc_Subtract_IntInt_ReturnValue = CallFunc_Subtract_IntInt_ReturnValue;
	Parms.CallFunc_LessEqual_IntInt_ReturnValue = CallFunc_LessEqual_IntInt_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CarouselPaginator_CM.WBP_CarouselPaginator_CM_C.UpdateNavButtonStates
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CarouselPaginator_CM_C::UpdateNavButtonStates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CarouselPaginator_CM_C", "UpdateNavButtonStates");

	UObject::ProcessEvent(Func, nullptr);
}

}

