#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GuildActivityTracker

#include "Basic.hpp"

#include "WBP_GuildActivityTracker_classes.hpp"
#include "WBP_GuildActivityTracker_parameters.hpp"


namespace SDK
{

// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.BindGuildQuestsChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldBind                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVAL_PlayerGuildComponent*        LocalComponent                                         (Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TDelegate<void(class UVAL_PlayerGuildComponent* PlayerGuildComponent)>K2Node_CreateDelegate_OutputDelegate                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EValeriaFuncResult                      CallFunc_GetValeriaPlayerController_OutResult          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AValeriaPlayerController*         CallFunc_GetValeriaPlayerController_ReturnValue        (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_SwitchEnum_CmpSuccess                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVAL_PlayerGuildComponent*        CallFunc_GetComponentByClass_ReturnValue               (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::BindGuildQuestsChanged(bool ShouldBind, class UVAL_PlayerGuildComponent* LocalComponent, TDelegate<void(class UVAL_PlayerGuildComponent* PlayerGuildComponent)> K2Node_CreateDelegate_OutputDelegate, EValeriaFuncResult CallFunc_GetValeriaPlayerController_OutResult, class AValeriaPlayerController* CallFunc_GetValeriaPlayerController_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, class UVAL_PlayerGuildComponent* CallFunc_GetComponentByClass_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "BindGuildQuestsChanged");

	Params::WBP_GuildActivityTracker_C_BindGuildQuestsChanged Parms{};

	Parms.ShouldBind = ShouldBind;
	Parms.LocalComponent = LocalComponent;
	Parms.K2Node_CreateDelegate_OutputDelegate = K2Node_CreateDelegate_OutputDelegate;
	Parms.CallFunc_GetValeriaPlayerController_OutResult = CallFunc_GetValeriaPlayerController_OutResult;
	Parms.CallFunc_GetValeriaPlayerController_ReturnValue = CallFunc_GetValeriaPlayerController_ReturnValue;
	Parms.K2Node_SwitchEnum_CmpSuccess = K2Node_SwitchEnum_CmpSuccess;
	Parms.CallFunc_GetComponentByClass_ReturnValue = CallFunc_GetComponentByClass_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.CreatePinWidgetFromQuest
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVAL_PlayerGuildQuest            Quest                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UVAL_PlayerGuildComponent*        PlayerGuildComp                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UWBP_ListEntry_GuildActivityTracker_C*CallFunc_Create_ReturnValue                            (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsQuestPinned_ReturnValue                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPanelSlot*                       CallFunc_AddChild_ReturnValue                          (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::CreatePinWidgetFromQuest(struct FVAL_PlayerGuildQuest& Quest, class UVAL_PlayerGuildComponent* PlayerGuildComp, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UWBP_ListEntry_GuildActivityTracker_C* CallFunc_Create_ReturnValue, bool CallFunc_IsQuestPinned_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "CreatePinWidgetFromQuest");

	Params::WBP_GuildActivityTracker_C_CreatePinWidgetFromQuest Parms{};

	Parms.Quest = std::move(Quest);
	Parms.PlayerGuildComp = PlayerGuildComp;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_Create_ReturnValue = CallFunc_Create_ReturnValue;
	Parms.CallFunc_IsQuestPinned_ReturnValue = CallFunc_IsQuestPinned_ReturnValue;
	Parms.CallFunc_AddChild_ReturnValue = CallFunc_AddChild_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GuildActivityTracker_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.ExecuteUbergraph_WBP_GuildActivityTracker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsFeatureEnabled_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Variable                                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_LessEqual_IntInt_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable_1                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue_1                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue_2                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable_1                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable_2                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue_3                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable_2                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVAL_PlayerGuildComponent*        K2Node_CustomEvent_PlayerGuildComp                     (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EValeriaFuncResult                      CallFunc_GetValeriaPlayerController_OutResult          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AValeriaPlayerController*         CallFunc_GetValeriaPlayerController_ReturnValue        (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UVAL_PlayerGuildComponent*        CallFunc_GetComponentByClass_ReturnValue               (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FVAL_PlayerGuildQuest            CallFunc_Array_Get_Item                                ()
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVAL_PlayerGuildQuest            CallFunc_Array_Get_Item_1                              ()
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue_1                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVAL_PlayerGuildQuest            CallFunc_Array_Get_Item_2                              ()
// bool                                    CallFunc_Less_IntInt_ReturnValue_1                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue_2                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_SwitchEnum_CmpSuccess                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Less_IntInt_ReturnValue_2                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UWBP_ListEntry_GuildActivityTracker_C*CallFunc_Create_ReturnValue                            (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UVerticalBoxSlot*                 CallFunc_AddChildToVerticalBox_ReturnValue             (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsFeatureEnabled_ReturnValue_1                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsFeatureEnabled_ReturnValue_2                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::ExecuteUbergraph_WBP_GuildActivityTracker(int32 EntryPoint, bool CallFunc_IsFeatureEnabled_ReturnValue, int32 Temp_int_Variable, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_2, bool K2Node_Event_IsDesignTime, class UVAL_PlayerGuildComponent* K2Node_CustomEvent_PlayerGuildComp, EValeriaFuncResult CallFunc_GetValeriaPlayerController_OutResult, class AValeriaPlayerController* CallFunc_GetValeriaPlayerController_ReturnValue, class UVAL_PlayerGuildComponent* CallFunc_GetComponentByClass_ReturnValue, const struct FVAL_PlayerGuildQuest& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, const struct FVAL_PlayerGuildQuest& CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, const struct FVAL_PlayerGuildQuest& CallFunc_Array_Get_Item_2, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_Less_IntInt_ReturnValue_2, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UWBP_ListEntry_GuildActivityTracker_C* CallFunc_Create_ReturnValue, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, bool CallFunc_IsFeatureEnabled_ReturnValue_1, bool CallFunc_IsFeatureEnabled_ReturnValue_2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "ExecuteUbergraph_WBP_GuildActivityTracker");

	Params::WBP_GuildActivityTracker_C_ExecuteUbergraph_WBP_GuildActivityTracker Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_IsFeatureEnabled_ReturnValue = CallFunc_IsFeatureEnabled_ReturnValue;
	Parms.Temp_int_Variable = Temp_int_Variable;
	Parms.CallFunc_LessEqual_IntInt_ReturnValue = CallFunc_LessEqual_IntInt_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.Temp_int_Loop_Counter_Variable_1 = Temp_int_Loop_Counter_Variable_1;
	Parms.CallFunc_Add_IntInt_ReturnValue_1 = CallFunc_Add_IntInt_ReturnValue_1;
	Parms.CallFunc_Add_IntInt_ReturnValue_2 = CallFunc_Add_IntInt_ReturnValue_2;
	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.Temp_int_Array_Index_Variable_1 = Temp_int_Array_Index_Variable_1;
	Parms.Temp_int_Loop_Counter_Variable_2 = Temp_int_Loop_Counter_Variable_2;
	Parms.CallFunc_Add_IntInt_ReturnValue_3 = CallFunc_Add_IntInt_ReturnValue_3;
	Parms.Temp_int_Array_Index_Variable_2 = Temp_int_Array_Index_Variable_2;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;
	Parms.K2Node_CustomEvent_PlayerGuildComp = K2Node_CustomEvent_PlayerGuildComp;
	Parms.CallFunc_GetValeriaPlayerController_OutResult = CallFunc_GetValeriaPlayerController_OutResult;
	Parms.CallFunc_GetValeriaPlayerController_ReturnValue = CallFunc_GetValeriaPlayerController_ReturnValue;
	Parms.CallFunc_GetComponentByClass_ReturnValue = CallFunc_GetComponentByClass_ReturnValue;
	Parms.CallFunc_Array_Get_Item = std::move(CallFunc_Array_Get_Item);
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.CallFunc_Array_Get_Item_1 = std::move(CallFunc_Array_Get_Item_1);
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.CallFunc_Array_Length_ReturnValue_1 = CallFunc_Array_Length_ReturnValue_1;
	Parms.CallFunc_Array_Get_Item_2 = std::move(CallFunc_Array_Get_Item_2);
	Parms.CallFunc_Less_IntInt_ReturnValue_1 = CallFunc_Less_IntInt_ReturnValue_1;
	Parms.CallFunc_Array_Length_ReturnValue_2 = CallFunc_Array_Length_ReturnValue_2;
	Parms.K2Node_SwitchEnum_CmpSuccess = K2Node_SwitchEnum_CmpSuccess;
	Parms.CallFunc_Less_IntInt_ReturnValue_2 = CallFunc_Less_IntInt_ReturnValue_2;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_Create_ReturnValue = CallFunc_Create_ReturnValue;
	Parms.CallFunc_AddChildToVerticalBox_ReturnValue = CallFunc_AddChildToVerticalBox_ReturnValue;
	Parms.CallFunc_IsFeatureEnabled_ReturnValue_1 = CallFunc_IsFeatureEnabled_ReturnValue_1;
	Parms.CallFunc_IsFeatureEnabled_ReturnValue_2 = CallFunc_IsFeatureEnabled_ReturnValue_2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.HandleOnGuildPinnedQuestsChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVAL_PlayerGuildComponent*        PlayerGuildComponent                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::HandleOnGuildPinnedQuestsChanged(class UVAL_PlayerGuildComponent* PlayerGuildComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "HandleOnGuildPinnedQuestsChanged");

	Params::WBP_GuildActivityTracker_C_HandleOnGuildPinnedQuestsChanged Parms{};

	Parms.PlayerGuildComponent = PlayerGuildComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.InitializeFromCharacter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVAL_PlayerGuildComponent*        PlayerGuildComp                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TDelegate<void(class UVAL_PlayerGuildComponent* PlayerGuildComponent)>K2Node_CreateDelegate_OutputDelegate                   (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::InitializeFromCharacter(class UVAL_PlayerGuildComponent* PlayerGuildComp, TDelegate<void(class UVAL_PlayerGuildComponent* PlayerGuildComponent)> K2Node_CreateDelegate_OutputDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "InitializeFromCharacter");

	Params::WBP_GuildActivityTracker_C_InitializeFromCharacter Parms{};

	Parms.PlayerGuildComp = PlayerGuildComp;
	Parms.K2Node_CreateDelegate_OutputDelegate = K2Node_CreateDelegate_OutputDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GuildActivityTracker_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "PreConstruct");

	Params::WBP_GuildActivityTracker_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuildActivityTracker.WBP_GuildActivityTracker_C.RebuildQuests
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVAL_PlayerGuildComponent*        PlayerGuildComp                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GuildActivityTracker_C::RebuildQuests(class UVAL_PlayerGuildComponent* PlayerGuildComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuildActivityTracker_C", "RebuildQuests");

	Params::WBP_GuildActivityTracker_C_RebuildQuests Parms{};

	Parms.PlayerGuildComp = PlayerGuildComp;

	UObject::ProcessEvent(Func, &Parms);
}

}

