#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ListEntry_Social_Block_CM

#include "Basic.hpp"

#include "WBP_ListEntry_Social_Block_CM_classes.hpp"
#include "WBP_ListEntry_Social_Block_CM_parameters.hpp"


namespace SDK
{

// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unblock_K2Node_ComponentBoundEvent_1_OnFocus__DelegateSignature
// (BlueprintEvent)

void UWBP_ListEntry_Social_Block_CM_C::BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unblock_K2Node_ComponentBoundEvent_1_OnFocus__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unblock_K2Node_ComponentBoundEvent_1_OnFocus__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unfollow_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_ListEntry_Social_Block_CM_C::BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unfollow_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BndEvt__WBP_ListEntry_Social_Block_CM_Button_Secondary_Unfollow_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_4_OnCustomNavigationGroupInitialized__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class US6UI_CustomNavigationGroup*      NavGroup                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_4_OnCustomNavigationGroupInitialized__DelegateSignature(class US6UI_CustomNavigationGroup* NavGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_4_OnCustomNavigationGroupInitialized__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_4_OnCustomNavigationGroupInitialized__DelegateSignature Parms{};

	Parms.NavGroup = NavGroup;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_5_OnNavigated__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class US6UI_CustomNavigationGroup*      NavGroup                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_5_OnNavigated__DelegateSignature(class US6UI_CustomNavigationGroup* NavGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_5_OnNavigated__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_BndEvt__WBP_ListEntry_Social_Block_CM_CustomNavigationGroup_Unblock_K2Node_ComponentBoundEvent_5_OnNavigated__DelegateSignature Parms{};

	Parms.NavGroup = NavGroup;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BndEvt__WBP_ListEntry_Social_Block_CM_WBP_PlayerCharacterRow_CM_K2Node_ComponentBoundEvent_3_OnCharacterProfileImageClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PlayerCharacterProfileImage_CM_C*CharacterProfileImageWidget                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::BndEvt__WBP_ListEntry_Social_Block_CM_WBP_PlayerCharacterRow_CM_K2Node_ComponentBoundEvent_3_OnCharacterProfileImageClicked__DelegateSignature(class UWBP_PlayerCharacterProfileImage_CM_C* CharacterProfileImageWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BndEvt__WBP_ListEntry_Social_Block_CM_WBP_PlayerCharacterRow_CM_K2Node_ComponentBoundEvent_3_OnCharacterProfileImageClicked__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_BndEvt__WBP_ListEntry_Social_Block_CM_WBP_PlayerCharacterRow_CM_K2Node_ComponentBoundEvent_3_OnCharacterProfileImageClicked__DelegateSignature Parms{};

	Parms.CharacterProfileImageWidget = CharacterProfileImageWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_ListEntry_Social_Block_CM_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BP_OnItemExpansionChanged");

	Params::WBP_ListEntry_Social_Block_CM_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "BP_OnItemSelectionChanged");

	Params::WBP_ListEntry_Social_Block_CM_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ListEntry_Social_Block_CM_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.ExecuteUbergraph_WBP_ListEntry_Social_Block_CM
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  K2Node_MakeArray_Array                                 (ConstParm, ReferenceParm, ContainsInstancedReference)
// bool                                    K2Node_Event_bIsExpanded                               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_bIsSelected                               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          K2Node_Event_ListItemObject                            (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UListItem_SocialConnection_C*     K2Node_DynamicCast_AsList_Item_Social_Connection       (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_PlayerCharacterProfileImage_CM_C*K2Node_ComponentBoundEvent_CharacterProfileImageWidget (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FF_CommonUIButtonPrompt          K2Node_MakeStruct_F_CommonUIButtonPrompt               (HasGetValueTypeHash)
// struct FF_CommonUIButtonPrompt          K2Node_MakeStruct_F_CommonUIButtonPrompt_1             (HasGetValueTypeHash)
// class UVAL_FriendsManager*              CallFunc_GetLocalPlayerSubsystem_ReturnValue           (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FF_CommonUIButtonPrompt>  K2Node_MakeArray_Array_1                               (ReferenceParm)
// EVAL_SocialBlockError                   CallFunc_RequestBlockUser_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class US6UI_CustomNavigationGroup*      K2Node_ComponentBoundEvent_NavGroup_1                  (ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class US6UI_CustomNavigationGroup*      K2Node_ComponentBoundEvent_NavGroup                    (ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::ExecuteUbergraph_WBP_ListEntry_Social_Block_CM(int32 EntryPoint, TArray<class UWidget*>& K2Node_MakeArray_Array, bool K2Node_Event_bIsExpanded, bool K2Node_Event_bIsSelected, class UObject* K2Node_Event_ListItemObject, class UListItem_SocialConnection_C* K2Node_DynamicCast_AsList_Item_Social_Connection, bool K2Node_DynamicCast_bSuccess, class UWBP_PlayerCharacterProfileImage_CM_C* K2Node_ComponentBoundEvent_CharacterProfileImageWidget, const struct FF_CommonUIButtonPrompt& K2Node_MakeStruct_F_CommonUIButtonPrompt, const struct FF_CommonUIButtonPrompt& K2Node_MakeStruct_F_CommonUIButtonPrompt_1, class UVAL_FriendsManager* CallFunc_GetLocalPlayerSubsystem_ReturnValue, TArray<struct FF_CommonUIButtonPrompt>& K2Node_MakeArray_Array_1, EVAL_SocialBlockError CallFunc_RequestBlockUser_ReturnValue, class US6UI_CustomNavigationGroup* K2Node_ComponentBoundEvent_NavGroup_1, class US6UI_CustomNavigationGroup* K2Node_ComponentBoundEvent_NavGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "ExecuteUbergraph_WBP_ListEntry_Social_Block_CM");

	Params::WBP_ListEntry_Social_Block_CM_C_ExecuteUbergraph_WBP_ListEntry_Social_Block_CM Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_MakeArray_Array = std::move(K2Node_MakeArray_Array);
	Parms.K2Node_Event_bIsExpanded = K2Node_Event_bIsExpanded;
	Parms.K2Node_Event_bIsSelected = K2Node_Event_bIsSelected;
	Parms.K2Node_Event_ListItemObject = K2Node_Event_ListItemObject;
	Parms.K2Node_DynamicCast_AsList_Item_Social_Connection = K2Node_DynamicCast_AsList_Item_Social_Connection;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.K2Node_ComponentBoundEvent_CharacterProfileImageWidget = K2Node_ComponentBoundEvent_CharacterProfileImageWidget;
	Parms.K2Node_MakeStruct_F_CommonUIButtonPrompt = std::move(K2Node_MakeStruct_F_CommonUIButtonPrompt);
	Parms.K2Node_MakeStruct_F_CommonUIButtonPrompt_1 = std::move(K2Node_MakeStruct_F_CommonUIButtonPrompt_1);
	Parms.CallFunc_GetLocalPlayerSubsystem_ReturnValue = CallFunc_GetLocalPlayerSubsystem_ReturnValue;
	Parms.K2Node_MakeArray_Array_1 = std::move(K2Node_MakeArray_Array_1);
	Parms.CallFunc_RequestBlockUser_ReturnValue = CallFunc_RequestBlockUser_ReturnValue;
	Parms.K2Node_ComponentBoundEvent_NavGroup_1 = K2Node_ComponentBoundEvent_NavGroup_1;
	Parms.K2Node_ComponentBoundEvent_NavGroup = K2Node_ComponentBoundEvent_NavGroup;

	UObject::ProcessEvent(Func, &Parms);

	K2Node_MakeArray_Array_1 = std::move(Parms.K2Node_MakeArray_Array_1);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)
// struct FEventReply                      CallFunc_Handled_ReturnValue                           ()

struct FEventReply UWBP_ListEntry_Social_Block_CM_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent, const struct FEventReply& CallFunc_Handled_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "OnFocusReceived");

	Params::WBP_ListEntry_Social_Block_CM_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);
	Parms.CallFunc_Handled_ReturnValue = std::move(CallFunc_Handled_ReturnValue);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.OnInspectPlayerCharacter__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_ListEntry_Social_Block_CM_C* Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FUniqueNetIdRepl                 UserId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::OnInspectPlayerCharacter__DelegateSignature(class UWBP_ListEntry_Social_Block_CM_C* Widget, const struct FUniqueNetIdRepl& UserId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "OnInspectPlayerCharacter__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_OnInspectPlayerCharacter__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.UserId = std::move(UserId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "OnListItemObjectSet");

	Params::WBP_ListEntry_Social_Block_CM_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.OnMarkFocusUI__DelegateSignature
// (Public, Delegate, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<struct FF_CommonUIButtonPrompt>  UIPrompt                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ListEntry_Social_Block_CM_C::OnMarkFocusUI__DelegateSignature(class UWidget* Widget, TArray<struct FF_CommonUIButtonPrompt>& UIPrompt)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "OnMarkFocusUI__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_OnMarkFocusUI__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.UIPrompt = std::move(UIPrompt);

	UObject::ProcessEvent(Func, &Parms);

	UIPrompt = std::move(Parms.UIPrompt);
}


// Function WBP_ListEntry_Social_Block_CM.WBP_ListEntry_Social_Block_CM_C.OnRemoveFriendClicked__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_ListEntry_Social_Block_CM_C* Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FUniqueNetIdRepl                 UserId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_ListEntry_Social_Block_CM_C::OnRemoveFriendClicked__DelegateSignature(class UWBP_ListEntry_Social_Block_CM_C* Widget, const struct FUniqueNetIdRepl& UserId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ListEntry_Social_Block_CM_C", "OnRemoveFriendClicked__DelegateSignature");

	Params::WBP_ListEntry_Social_Block_CM_C_OnRemoveFriendClicked__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.UserId = std::move(UserId);

	UObject::ProcessEvent(Func, &Parms);
}

}

