#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealthSlot

#include "Basic.hpp"

#include "WBP_HealthSlot_classes.hpp"
#include "WBP_HealthSlot_parameters.hpp"


namespace SDK
{

// Function WBP_HealthSlot.WBP_HealthSlot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HealthSlot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthSlot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HealthSlot.WBP_HealthSlot_C.ExecuteUbergraph_WBP_HealthSlot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         CallFunc_GetDynamicMaterial_ReturnValue                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HealthSlot_C::ExecuteUbergraph_WBP_HealthSlot(int32 EntryPoint, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthSlot_C", "ExecuteUbergraph_WBP_HealthSlot");

	Params::WBP_HealthSlot_C_ExecuteUbergraph_WBP_HealthSlot Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_GetDynamicMaterial_ReturnValue = CallFunc_GetDynamicMaterial_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HealthSlot.WBP_HealthSlot_C.SetPercent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Percent                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         CallFunc_GetDynamicMaterial_ReturnValue                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   CallFunc_SetScalarParameterValue_Value_ImplicitCast    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealthSlot_C::SetPercent(double Percent, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue, float CallFunc_SetScalarParameterValue_Value_ImplicitCast)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthSlot_C", "SetPercent");

	Params::WBP_HealthSlot_C_SetPercent Parms{};

	Parms.Percent = Percent;
	Parms.CallFunc_GetDynamicMaterial_ReturnValue = CallFunc_GetDynamicMaterial_ReturnValue;
	Parms.CallFunc_SetScalarParameterValue_Value_ImplicitCast = CallFunc_SetScalarParameterValue_Value_ImplicitCast;

	UObject::ProcessEvent(Func, &Parms);
}

}

